#!/bin/zsh

dotfiles_dir=~/dotfiles    # dotfiles directory
backup_dir=~/dotfiles_old  # old dotfiles backup directory
nvim_dir=~/.config/nvim
atom_dir=~/.atom
# list of files/folders to symlink in homedir
files=('.tmux.conf' '.vimrc' '.atom/keymap.cson' '.config/nvim/init.vim')

# create dotfiles_old in homedir
echo "Creating $backup_dir for backup of any existing dotfiles"
mkdir -p $backup_dir

echo "Creating neovim config directory if it doesn't exist already"
mkdir -p $nvim_dir

echo "Creating atom config directory if it doesn't exist already"
mkdir -p $atom_dir

echo "Moving any existing dotfiles to $backup_dir"
for file in $files; do
    echo "file: $file"
    mv ~/$file ~/dotfiles_old/

    echo "Creating symlink to $file in home directory."
    ln -s $dotfiles_dir/$file ~/$file
done
