# Homebrew Bundle github:
# https://github.com/Homebrew/homebrew-bundle
#
# Browse formula:
# https://formulae.brew.sh
#
# MAS github:
# https://github.com/mas-cli/mas

brew "font-meslo-lg-nerd-font"
brew "fzf"
brew "neovim"
brew "ripgrep"
brew "zsh"

cask "1password"
cask "alfred"
cask "bettertouchtool"
cask "brave-browser"
cask "google-chrome"
cast "istat-menus"
cask "iterm2"
cask "karabiner-elements"

# Mac App Store
mas "Bear Markdown Notes", id: 1091189122
mas "Moom", id: 419330170
