export EDITOR="nvim"
export USER=$(whoami)

# PATH
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="/usr/local/opt/postgresql@9.5/bin:$PATH"
export PATH=".git/safe/../../bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# ZSH
# needs to be run before other things
ZSH_THEME="agnoster"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
plugins=(git)
export ZSH=~/.oh-my-zsh
export UPDATE_ZSH_DAYS=30
source $ZSH/oh-my-zsh.sh

# Aliases
alias vim=$EDITOR
alias zshrc="$EDITOR ~/.zshrc"
alias downloads="open ~/Downloads"
alias vimrc="$EDITOR ~/.vimrc"
alias nvimrc="$EDITOR ~/.config/nvim/init.vim"
alias redisstart='sudo launchctl start io.redis.redis-server'
alias redisstop='sudo launchctl stop io.redis.redis-server'
alias rabbitstop='launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist'
alias rabbitstart='launchctl load ~/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist'
alias nuke_merged_branches="git branch --merged | egrep -v '(^\*|master|develop|staging)' | xargs git branch -d"

# Use ripgrep for searches
#   --hidden: show hidden files
#   --follow: follow symlink
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Load all startup scripts in ~/.zshinit dir
for file in $HOME/.zshinit/*.sh; do
  echo "loading $file"
  . "$file";
done
